security:
    # Providers define how users are fetched (you can use in-memory, database, or other services)
    providers:
        users_in_memory:
            memory: ~  # Use in-memory users, replace with your DB provider in production

    firewalls:
        # Disable security for assets like the profiler, CSS, images, and JS
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # API firewall for routes under /api
        api:
            pattern: ^/api  # Apply to all routes under /api
            stateless: true  # We don't use sessions for API requests

    # Access control rules to protect the /api routes
    access_control:
        - { path: ^/api, roles: ROLE_USER }
